name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 15 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_skipped: blog-comments, dart-study, dltkdgns00, dltkdgns00.github.io, dltkdgns00.tk, ember_quest, flutter_study, my-first-web-site, MyFirstiOS, node.js-express, node.js-mysql-study, node.js-study, study-python
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_topics_sort: activity
          plugin_stars: yes
          plugin_stars_limit: 2
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          
